controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

category:
    path: /category
    controller: App\Controller\CategoryController::index

product:
    path: /product
    controller: App\Controller\ProductController::index

app_homepage:
    path: /
    controller: App\Controller\HomePageController::index